const SETTINGS_KEY='salary-survival-cloud-settings-v1';
let clientPromise;
export function cloudSettings(){try{return JSON.parse(localStorage.getItem(SETTINGS_KEY)||'null')}catch{return null}}
export function saveCloudSettings(url,key){const cleanUrl=String(url||'').trim().replace(/\/$/,'');const cleanKey=String(key||'').trim();if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(cleanUrl)||!cleanKey)throw Error('Enter your Supabase project URL and publishable key.');const settings={url:cleanUrl,key:cleanKey};localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));clientPromise=null;return settings}
async function client(){const cfg=cloudSettings();if(!cfg)throw Error('Set up cloud sync with your Supabase project first.');if(!clientPromise)clientPromise=import('https://esm.sh/@supabase/supabase-js@2').then(({createClient})=>createClient(cfg.url,cfg.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}));return clientPromise}
export async function cloudUser(){const c=await client(),{data,error}=await c.auth.getUser();if(error)throw error;return data.user}
export async function cloudSession(){const c=await client(),{data,error}=await c.auth.getSession();if(error)throw error;return data.session}
export async function sendCloudSignIn(email){const c=await client();return c.auth.signInWithOtp({email:String(email).trim(),options:{emailRedirectTo:location.origin+location.pathname}})}
export async function signOutCloud(){const c=await client();return c.auth.signOut()}
export async function pushCloudSnapshot(snapshot){const c=await client(),user=await cloudUser();if(!user)throw Error('Open the sign-in link sent to your email first.');const {error}=await c.from('user_finance_snapshots').upsert({user_id:user.id,snapshot,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(error)throw error;return new Date().toISOString()}
export async function pullCloudSnapshot(){const c=await client(),user=await cloudUser();if(!user)throw Error('Open the sign-in link sent to your email first.');const {data,error}=await c.from('user_finance_snapshots').select('snapshot,updated_at').eq('user_id',user.id).maybeSingle();if(error)throw error;if(!data)throw Error('No cloud backup exists for this account yet.');return data}
export async function monoStatus(){const c=await client(),user=await cloudUser();if(!user)throw Error('Sign in to use bank linking.');const {data,error}=await c.from('mono_account_links').select('status,institution,retrieved_data').eq('user_id',user.id).maybeSingle();if(error)throw error;return data}
export async function startMonoLink(redirectUrl,consent=false){const c=await client();const {data,error}=await c.functions.invoke('mono-link',{body:{redirectUrl,consent}});if(error)throw error;if(!data?.url)throw Error('The bank-link service did not return a link.');return data.url}
export async function monoTransactions(start,end){const c=await client(),{data,error}=await c.functions.invoke('mono-transactions',{body:{start,end}});if(error)throw error;return data?.transactions||[]}
export async function disconnectMono(){const c=await client(),{data,error}=await c.functions.invoke('mono-disconnect',{body:{}});if(error)throw error;return data}
export async function deleteCloudSnapshot(){const c=await client(),user=await cloudUser();if(!user)throw Error('Open the sign-in link sent to your email first.');const {error}=await c.from('user_finance_snapshots').delete().eq('user_id',user.id);if(error)throw error}
