import {EXPENSES,initialPlan,initialPriorities} from './game.js?planner-cloud=20261001';
export const PLANNER_KEY='salary-survival-monthly-planner-v1';
const FLEX_CATEGORIES=new Set(['food','transport','family','fun']);
export function localDateValue(date=new Date()){const d=new Date(date);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
export function createInitialPlanner(income=0){const payday=new Date();payday.setDate(payday.getDate()+30);return {income, payDate:localDateValue(payday), ready:false, expenses:initialPlan(income), priorities:initialPriorities(), transactions:[]}}
export function normalizePlanner(p){if(!p||typeof p!=='object'||!Number.isFinite(Number(p.income))||Number(p.income)<0)return null;const expenses={...initialPlan(Number(p.income)),...(p.expenses||{})};if(EXPENSES.some(x=>!Number.isFinite(Number(expenses[x.id]))||Number(expenses[x.id])<0))return null;const priorities={...initialPriorities(),...Object.fromEntries(Object.entries(p.priorities||{}).filter(([id,value])=>EXPENSES.some(x=>x.id===id)&&['protect','important','reduce'].includes(value)))};const transactions=Array.isArray(p.transactions)?p.transactions.filter(x=>x&&typeof x.id==='string'&&EXPENSES.some(c=>c.id===x.category)&&Number.isFinite(Number(x.amount))&&Number(x.amount)>0&&Number(x.amount)<=1000000000).slice(-2000).map(x=>({id:x.id,category:x.category,amount:Math.round(Number(x.amount)),date:/^\d{4}-\d{2}-\d{2}$/.test(x.date)?x.date:localDateValue(),note:typeof x.note==='string'?x.note.slice(0,120):'',externalId:typeof x.externalId==='string'?x.externalId.slice(0,160):''})):[];return {income:Math.round(Number(p.income)),payDate:/^\d{4}-\d{2}-\d{2}$/.test(p.payDate||'')?p.payDate:localDateValue(),ready:Boolean(p.ready),expenses:Object.fromEntries(EXPENSES.map(x=>[x.id,Math.round(Number(expenses[x.id]))])),priorities,transactions}}
export function loadPlanner(){try{return normalizePlanner(JSON.parse(localStorage.getItem(PLANNER_KEY)||'null'))}catch{return null}}
export function savePlanner(p){const clean=normalizePlanner(p);if(!clean)throw Error('Could not save this monthly plan. Check your income and budget amounts.');localStorage.setItem(PLANNER_KEY,JSON.stringify(clean));return clean}
export function transactionTotals(p){return Object.fromEntries(EXPENSES.map(x=>[x.id,p.transactions.filter(t=>t.category===x.id).reduce((sum,t)=>sum+t.amount,0)]))}
export function safeToSpend(p,today=new Date()){const totals=transactionTotals(p),now=new Date(today);now.setHours(0,0,0,0);const payday=new Date(`${p.payDate}T00:00:00`),daysLeft=Math.max(1,Math.ceil((payday-now)/86400000)+1),allocated=EXPENSES.reduce((sum,x)=>sum+p.expenses[x.id],0),overBudget=EXPENSES.reduce((sum,x)=>sum+Math.max(0,totals[x.id]-p.expenses[x.id]),0),buffer=Math.max(0,p.income-allocated-overBudget),flexible=Array.from(FLEX_CATEGORIES).reduce((sum,id)=>sum+Math.max(0,p.expenses[id]-totals[id]),0),daily=(buffer+flexible)/daysLeft,todayKey=localDateValue(now),spentToday=p.transactions.filter(t=>FLEX_CATEGORIES.has(t.category)&&t.date===todayKey).reduce((sum,t)=>sum+t.amount,0);return {daysLeft,daily:p.ready?Math.floor(daily):0,spentToday,remainingToday:p.ready?Math.max(0,Math.floor(daily-spentToday)):0,totals,buffer}}
function csvRows(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')quoted=false;else cell+=c}else if(c==='"')quoted=true;else if(c===','){row.push(cell.trim());cell=''}else if(c==='\n'){row.push(cell.trim());if(row.some(x=>x))rows.push(row);row=[];cell=''}else if(c!=='\r')cell+=c}row.push(cell.trim());if(row.some(x=>x))rows.push(row);return rows}
function dateISO(value){const s=String(value||'').trim(),m=s.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);let d;if(m){const [,day,month,year]=m;d=new Date(Number(year),Number(month)-1,Number(day))}else d=new Date(s);return Number.isNaN(d.getTime())?localDateValue():localDateValue(d)}
function numberValue(value){const s=String(value||'').replace(/[₦$£€,\s]/g,'').replace(/[()]/g,'');const n=Number(s);return Number.isFinite(n)?n:0}
function matchCategory(value){const s=String(value||'').trim().toLowerCase();if(!s)return null;return EXPENSES.find(x=>x.id===s||x.name.toLowerCase()===s||x.name.toLowerCase().includes(s)||s.includes(x.id))?.id}
export function parseSpendingCsv(text,defaultCategory='food'){const rows=csvRows(String(text).replace(/^\uFEFF/,''));if(rows.length<2)throw Error('The CSV needs a header row and at least one transaction.');const headers=rows[0].map(x=>x.toLowerCase().replace(/[^a-z]/g,'')),find=(names)=>headers.findIndex(h=>names.includes(h)),dateAt=find(['date','transactiondate','valuedate','posteddate']),descAt=find(['description','details','narration','merchant','transactiondescription','name']),debitAt=find(['debit','debitamount','withdrawal','withdrawals','withdrawalamount','moneyout']),amountAt=find(['amount','value','transactionamount']);if(debitAt<0&&amountAt<0)throw Error('Could not find an Amount or Debit column in this CSV.');const catAt=find(['category','type']);return rows.slice(1).map(row=>{const raw=debitAt>=0?row[debitAt]:row[amountAt];const amount=numberValue(raw);const type=String(row[catAt]||'').toLowerCase();if(!amount||/credit|deposit|income|transfer in/.test(type))return null;return {category:matchCategory(row[catAt])||defaultCategory,amount:Math.round(Math.abs(amount)),date:dateISO(row[dateAt]),note:String(row[descAt]||'Imported transaction').slice(0,120)}}).filter(x=>x&&x.amount>0&&EXPENSES.some(c=>c.id===x.category))}
export function newTransactionId(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}
